### ISSUE TITLE
Cannot compile on rustc nightly 1.60

### ISSUE THREAD

**Issue by JakkuSakura** [monoio-rs/monoio#44]
```
rustc --version
rustc 1.60.0-nightly (bfe156467 2022-01-22)
```

```
error[E0271]: type mismatch resolving `<impl futures::Future<Output = [async output]> as futures::Future>::Output == ()`
  --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/monoio-0.0.3/src/stream/stream_ext.rs:44:30
   |
34 |           async move {
   |  ____________________-
35 | |             while let Some(item) = self.next().await {
36 | |                 (f)(item);
37 | |             }
38 | |         }
   | |_________- the found `async` block
...
44 |   type ForEachFut<T, Fut, F> = impl Future<Output = ()>;
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found associated type
   |
  ::: /home/jack/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:65:43
   |
65 |   pub const fn from_generator<T>(gen: T) -> impl Future<Output = T::Return>
   |                                             ------------------------------- the found opaque type
   |
   = note:    expected unit type `()`
           found associated type `<impl futures::Future<Output = [async output]> as futures::Future>::Output`
   = help: consider constraining the associated type `<impl futures::Future<Output = [async output]> as futures::Future>::Output` to `()`
   = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html


error[E0277]: the trait bound `T: stream::Stream` is not satisfied
  --> /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/monoio-0.0.3/src/stream/stream_ext.rs:44:30
   |
44 | type ForEachFut<T, Fut, F> = impl Future<Output = ()>;
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `stream::Stream` is not implemented for `T`
   |
help: consider restricting type parameter `T`
   |
44 | type ForEachFut<T: stream::Stream, Fut, F> = impl Future<Output = ()>;
   |                  ++++++++++++++++



```

**Comment by ihciah** [comment]
I tested and believe this is solved. For any problem please reopen it this issue.
